In [1]:
import numpy as np


# 1
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# 2
a = np.zeros((3, 3), dtype=np.uint32)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint32)

In [3]:
# 3
a = np.random.randint(1, 10, (5, 5))
a

array([[2, 9, 2, 5, 8],
       [2, 3, 4, 6, 8],
       [3, 6, 4, 9, 6],
       [5, 1, 5, 7, 7],
       [3, 6, 6, 3, 8]])

In [4]:
# 4
a = np.random.random((4, 4))
a

array([[0.26830076, 0.85866606, 0.50348308, 0.19372267],
       [0.85088535, 0.14611054, 0.80532549, 0.67745395],
       [0.24586596, 0.72497964, 0.97911771, 0.51869296],
       [0.23512304, 0.59486207, 0.18319091, 0.63708479]])

In [5]:
# 5
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)

print(a)
print(b)

print(a * b)
print(a - b)
print(a / b)

[3 5 9 2 9]
[6 6 9 8 7]
[18 30 81 16 63]
[-3 -1  0 -6  2]
[0.5        0.83333333 1.         0.25       1.28571429]


In [6]:
# 6
a = np.random.randint(1, 10, 7)
b = np.random.randint(1, 10, 7)

print(a)
print(b)

print(np.dot(a, b))

[2 9 5 4 3 9 2]
[7 1 8 2 3 7 4]
151


In [7]:
# 7
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))

print(a)
print(b)

print(np.dot(a, b))

[[5 3]
 [4 3]]
[[8 8 8]
 [3 6 5]]
[[49 58 55]
 [41 50 47]]


In [8]:
# 8
a = np.random.randint(1, 10, (3, 3))

print(a)

print(np.linalg.inv(a))

[[3 5 1]
 [9 2 4]
 [6 1 3]]
[[-0.16666667  1.16666667 -1.5       ]
 [ 0.25       -0.25        0.25      ]
 [ 0.25       -2.25        3.25      ]]


In [9]:
# 9
a = np.random.random((4, 4))

print(a)

print(a.T)

[[0.94043127 0.75777006 0.16406138 0.54412608]
 [0.44776669 0.45075977 0.60035361 0.83155331]
 [0.67012761 0.2967062  0.76488284 0.06365044]
 [0.00173173 0.55361041 0.23103964 0.86611717]]
[[0.94043127 0.44776669 0.67012761 0.00173173]
 [0.75777006 0.45075977 0.2967062  0.55361041]
 [0.16406138 0.60035361 0.76488284 0.23103964]
 [0.54412608 0.83155331 0.06365044 0.86611717]]


In [10]:
# 10
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, 4)

print(a)
print(b)

print(np.dot(a, b))

[[9 7 4 9]
 [8 7 1 6]
 [9 5 4 4]]
[6 3 3 1]
[96 78 85]


In [11]:
# 11
a = np.random.random((2, 3))
b = np.random.random(3)

print(a)
print(b)

print(np.dot(a, b))

[[0.0385998  0.28154154 0.45629738]
 [0.46161974 0.16516922 0.59621193]]
[0.2008524  0.01828393 0.59667341]
[0.28516106 0.45148118]


In [12]:
# 12
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print(a)
print(b)

print(a * b)

[[5 4]
 [3 7]]
[[3 1]
 [5 7]]
[[15  4]
 [15 49]]


In [13]:
#13
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print(a)
print(b)

print(np.dot(a, b))

[[8 7]
 [1 9]]
[[9 6]
 [5 4]]
[[107  76]
 [ 54  42]]


In [14]:
#14
a = np.random.randint(1, 100, (5, 5))

print(a)

print(a.sum())

[[91 93  5 43 58]
 [21  5 66 85 25]
 [41 13 97 60 77]
 [48  8 98 52 69]
 [24 29 15  8 82]]
1213


In [15]:
#15
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))

print(a)
print(b)

print(a - b)

[[4 2 2 6]
 [9 1 4 9]
 [2 2 5 8]
 [9 7 2 3]]
[[9 2 2 2]
 [2 3 4 1]
 [7 3 7 6]
 [9 2 9 4]]
[[-5  0  0  4]
 [ 7 -2  0  8]
 [-5 -1 -2  2]
 [ 0  5 -7 -1]]


In [16]:
# 16
a = np.random.random((3, 3))

print(a)

print(a.sum(axis=1))

[[0.36914554 0.3974092  0.27439266]
 [0.87544243 0.93023744 0.77425558]
 [0.80588995 0.02499589 0.52455008]]
[1.0409474  2.57993545 1.35543591]


In [17]:
# 17
a = np.random.randint(1, 100, (3, 4))

print(a)

print(np.square(a))

[[47 71 41 31]
 [44 83 91 57]
 [27 83 61 17]]
[[2209 5041 1681  961]
 [1936 6889 8281 3249]
 [ 729 6889 3721  289]]


In [18]:
# 18
a = np.random.randint(1, 50, size=(3, 4))

print(a)

print(np.sqrt(a))

[[11 39 47 21]
 [20 15 33 48]
 [18 10 37 16]]
[[3.31662479 6.244998   6.8556546  4.58257569]
 [4.47213595 3.87298335 5.74456265 6.92820323]
 [4.24264069 3.16227766 6.08276253 4.        ]]
